### ISSUE TITLE
gitignore is broken

### ISSUE THREAD

**Issue by TylerCarberry** [RowanACM/ACMApp#10]
There was a merge conflict in the gitignore file. Fix this asap before it causes more problems.

**Comment by SirSaunders** [comment]
is it broken? I thought I added a new one after I merged it in?
https://github.com/RowanACM/ACMApp/blob/master/.gitignore.orig

**Comment by SirSaunders** [comment]
never mind, found it. I never pushed it. Ill merge it in with the ios pods fix
